# Model Development

## Model Definition

The occupancy model uses a logistic linear mixed effects model framework for estimating the probability of occupancy in each catchment [@bolker2009; @zuur2009].

The model includes one fixed effect representing the estimated mean July stream temperature (see [Stream Temperature]), and a random effect intercept that varies by HUC8. The random effect is included to account for spatial variations in observed occupancy that are not explained by the mean July stream temperature.

The model is fit using the `glmer()` function of the `lme4` R package [@bates2015] using the following formula and parameters.

```r
lme4::glmer(
  presence ~ mean_jul_temp + (1 | huc8),
  family = binomial(link = "logit"),
  data = model_data,
  control = glmerControl(optimizer = "bobyqa")
)
```


## Model History

The original development of this model was based on a similar brook trout occupancy model that was developed using a Bayesian hierarchical framework to evaluate associations between various catchment and riparian characteristics as well as climate inputs and the occupancy probability in catchments within the state of Connecticut [@kanno2015]. 

Prior to version 2.0.0, the EcoSHEDS northeast brook trout occupancy model included a number of independent variables (i.e., covariates) representing land use (forest, agriculture, high intensity development), climate (summer precipitation), and drainage area. The earlier model versions also included the mean July stream temperature as estimated by the EcoSHEDS northeast stream temperature model. However, because the stream temperature model depended on a number of the same independent variables, the estimated effects in the occupancy model were often counter-intuitive due to cross-correlations between some covariates and the estimated stream temperature. 

Therefore, beginning with version 2.0.0, the brook trout occupancy model uses only the mean July stream temperature as the sole fixed effect. This change resulted in a small decrease in model accuracy, but provides more intuitive results and can be more easily applied for evaluating alternative climate or land use change scenarios.
